development:
  adapter: postgresql
  encoding: unicode
  database: formosa_development

test:
  adapter: postgresql
  encoding: unicode
  database: formosa_test

production:
  adapter: postgresql
  encoding: unicode
  database: formosa_production
